-- =============================================================================
-- Promotional banners: what an instructor announces, and who has closed it
-- =============================================================================
--
-- This project has no migration tool: the schema is maintained by Hibernate
-- (`spring.jpa.hibernate.ddl-auto=update`). Both tables below are new, so
-- Hibernate creates them on its own -- there is nothing to back-fill, no NOT
-- NULL column being added to populated data, and no constraint being added to
-- a table that already exists. This script exists so the change can be applied
-- deliberately, ahead of the deployment, on environments where that is
-- preferred to letting the application do it on first start.
--
-- RUN THIS BEFORE DEPLOYING THE NEW BUILD, against each environment:
--
--     psql "$DATABASE_URL" -f 2026-08-instructor-banners.sql
--
-- Afterwards Hibernate's own update finds everything in place and does nothing.
--
-- The script is idempotent and safe to re-run: every statement is guarded.
-- Nothing here changes existing data.
-- =============================================================================


-- --------------------------------------------------------------------------
-- 1. Banners
-- --------------------------------------------------------------------------
-- The status a banner is badged with -- draft, scheduled, active, expired,
-- inactive -- is deliberately NOT a column. It is derived on read from `draft`,
-- `enabled` and the window, so a scheduled banner needs nothing to wake up and
-- promote it and an expired one needs nothing to retire it.
--
-- start_at and end_at are both nullable, and their nulls mean something: no
-- start is "already running", no end is "until switched off". `timezone` is the
-- zone its owner authored those two in, kept so the editor can read the dates
-- back the way they were typed -- the instants themselves are absolute and it
-- is never an input to the scheduling decision.
--
-- instructor_id cascades: banners are an instructor's own announcements and
-- have no meaning once that profile is gone.

CREATE TABLE IF NOT EXISTS banners (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id     BIGINT       NOT NULL REFERENCES instructors (id) ON DELETE CASCADE,
    internal_name     VARCHAR(255) NOT NULL,
    title             VARCHAR(255) NOT NULL,
    description       TEXT,
    image_url         VARCHAR(1024),
    cta_label         VARCHAR(255),
    cta_url           VARCHAR(1024),
    start_at          TIMESTAMP(6),
    end_at            TIMESTAMP(6),
    timezone          VARCHAR(64)  NOT NULL,
    priority          INTEGER      NOT NULL,
    enabled           BOOLEAN      NOT NULL,
    dismissible       BOOLEAN      NOT NULL,
    display_frequency VARCHAR(32)  NOT NULL,
    draft             BOOLEAN      NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6)
);

-- The management list is always "this instructor's banners, in their order".
CREATE INDEX IF NOT EXISTS idx_banners_instructor_id ON banners (instructor_id);

-- Delivery reads across every instructor and sorts by position.
CREATE INDEX IF NOT EXISTS idx_banners_priority ON banners (priority);


-- --------------------------------------------------------------------------
-- 2. Dismissals
-- --------------------------------------------------------------------------
-- Only banners set to ONCE_PER_STUDENT produce rows here. That mode promises a
-- learner sees the banner once -- not once per browser -- so the refusal cannot
-- live in the browser that made it. EVERY_VISIT and ONCE_PER_SESSION are scoped
-- to a visit by definition and stay client-side, where re-showing after a
-- session ends is the intended behaviour rather than a bug.
--
-- Unique on (banner_id, student_id): dismissing on a second device is the same
-- fact as the first, not a second one.
--
-- banner_id cascades -- a refusal of a banner that no longer exists has nothing
-- left to describe. student_id does not: a learner row is never removed under a
-- dismissal, and silently dropping these would re-show banners people closed.

CREATE TABLE IF NOT EXISTS banner_dismissals (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banner_id    BIGINT       NOT NULL REFERENCES banners (id) ON DELETE CASCADE,
    student_id   BIGINT       NOT NULL REFERENCES students (id),
    dismissed_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_banner_dismissals_banner_student UNIQUE (banner_id, student_id)
);

-- Delivery asks "what has this learner already refused" once per request.
CREATE INDEX IF NOT EXISTS idx_banner_dismissals_student_id
    ON banner_dismissals (student_id);
