-- =============================================================================
-- Enrollment uniqueness, entitlements and subscription terms
-- =============================================================================
--
-- This project has no migration tool: the schema is maintained by Hibernate
-- (`spring.jpa.hibernate.ddl-auto=update`). Unlike the previous two scripts,
-- this one is NOT optional -- `ddl-auto=update` never adds a constraint to a
-- table that already exists, so the `enrollments` unique constraint in step 1
-- will not appear on its own, and the back-fill in step 4 is something
-- Hibernate could not do at all.
--
-- RUN THIS BEFORE DEPLOYING THE NEW BUILD, against each environment:
--
--     psql "$DATABASE_URL" -f 2026-08-enrollment-entitlements-and-subscriptions.sql
--
-- It runs after 2026-08-course-structure-and-quizzes.sql, which created
-- `subscription_plans` and added `courses.access_type`.
--
-- The script is idempotent and safe to re-run: every statement is guarded.
--
-- Nothing here removes data. Step 4 grants existing learners exactly the access
-- they already had, so no one loses a course they were enrolled in.
-- =============================================================================


-- --------------------------------------------------------------------------
-- 1. Enrollment uniqueness
-- --------------------------------------------------------------------------
-- A learner joins a course once. The service checked for an existing enrolment
-- before inserting, but two concurrent checkouts both pass that check -- only
-- the database can settle it.
--
-- Any duplicates already in the table are collapsed first, keeping the oldest
-- row (the one whose progress and enrolled_at describe the real history) and
-- deleting the rest. On a healthy database this deletes nothing.

DELETE FROM enrollments e
USING enrollments keeper
WHERE e.course_id = keeper.course_id
  AND e.student_id = keeper.student_id
  AND e.id > keeper.id;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_enrollments_course_student'
    ) THEN
        ALTER TABLE enrollments
            ADD CONSTRAINT uk_enrollments_course_student UNIQUE (course_id, student_id);
    END IF;
END $$;


-- --------------------------------------------------------------------------
-- 2. Entitlements
-- --------------------------------------------------------------------------
-- One row per learner per course: the standing right to open its content.
-- This is what every protected read is now decided against, which is why it is
-- unique -- access is a single current fact, not a history.
--
-- expires_at NULL means perpetual, which FREE and PURCHASE grants always are.
-- Only a subscription carries an end, and renewing moves this row's window
-- forward rather than adding a second row.
--
-- No ON DELETE CASCADE on student_id: losing a learner's proof of purchase
-- because a row elsewhere was deleted would be data loss. course_id cascades --
-- an entitlement to a course that no longer exists has nothing left to grant.

CREATE TABLE IF NOT EXISTS course_entitlements (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id            BIGINT       NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    student_id           BIGINT       NOT NULL REFERENCES students (id),
    source               VARCHAR(20)  NOT NULL,
    subscription_plan_id BIGINT       REFERENCES subscription_plans (id),
    starts_at            TIMESTAMP(6) NOT NULL,
    expires_at           TIMESTAMP(6),
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6),
    CONSTRAINT uk_course_entitlements_course_student UNIQUE (course_id, student_id)
);

-- No separate index on (course_id, student_id): Postgres backs the unique
-- constraint above with a btree index, and its leading columns are exactly what
-- the access check filters on.


-- --------------------------------------------------------------------------
-- 3. Subscription terms
-- --------------------------------------------------------------------------
-- One row per term bought. A term is never rewritten: renewing writes a new row
-- and marks the previous one EXPIRED, so the sequence is the record of what a
-- learner actually paid for and when.
--
-- price_paid is stored rather than read back through the plan: an instructor may
-- reprice a plan afterwards, and that must not rewrite what someone was charged.
--
-- payment_reference comes from the payment gateway. Payments are SIMULATED in
-- this application -- every reference it issues is prefixed `sim_`, so no row
-- here can be mistaken for one backed by an actual charge.

CREATE TABLE IF NOT EXISTS course_subscriptions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id            BIGINT         NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    student_id           BIGINT         NOT NULL REFERENCES students (id),
    subscription_plan_id BIGINT         NOT NULL REFERENCES subscription_plans (id),
    starts_at            TIMESTAMP(6)   NOT NULL,
    expires_at           TIMESTAMP(6)   NOT NULL,
    status               VARCHAR(20)    NOT NULL,
    price_paid           NUMERIC(38, 2) NOT NULL,
    payment_reference    VARCHAR(100),
    created_at           TIMESTAMP(6)   NOT NULL,
    updated_at           TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_course_subscriptions_student_course
    ON course_subscriptions (student_id, course_id);

CREATE INDEX IF NOT EXISTS idx_course_subscriptions_course_id
    ON course_subscriptions (course_id);


-- --------------------------------------------------------------------------
-- 4. Back-fill: every existing enrolment keeps the access it already had
-- --------------------------------------------------------------------------
-- Before this change, an enrolment WAS the access -- it never expired, whatever
-- the course's access type. Granting each existing enrolment a perpetual
-- entitlement preserves exactly that. Anything else would revoke access people
-- currently have, which is not a migration, it is a regression.
--
-- `source` records how the course is sold, so the row is honest about where the
-- access came from. SUBSCRIPTION courses are included on purpose and get a NULL
-- expires_at: no subscription was ever sold or charged for -- plans were
-- definitions only -- so there is no window to reconstruct and no basis for
-- cutting anyone off.
--
-- New checkouts from here on create their own rows with real windows.

INSERT INTO course_entitlements (course_id, student_id, source, starts_at, expires_at, created_at)
SELECT e.course_id,
       e.student_id,
       COALESCE(c.access_type, 'FREE'),
       e.enrolled_at,
       NULL,
       NOW()
FROM enrollments e
         JOIN courses c ON c.id = e.course_id
WHERE NOT EXISTS (
    SELECT 1
    FROM course_entitlements ce
    WHERE ce.course_id = e.course_id
      AND ce.student_id = e.student_id
);
