-- =============================================================================
-- Quiz attempts: graded submissions and the answers behind them
-- =============================================================================
--
-- This project has no migration tool: the schema is maintained by Hibernate
-- (`spring.jpa.hibernate.ddl-auto=update`). Hibernate creates these two tables
-- on its own -- they are new, so there is nothing to back-fill and no NOT NULL
-- column being added to populated data. This script exists so the change can be
-- applied deliberately, ahead of the deployment, on environments where that is
-- preferred to letting the application do it on first start.
--
-- RUN THIS BEFORE DEPLOYING THE NEW BUILD, against each environment:
--
--     psql "$DATABASE_URL" -f 2026-08-quiz-attempts-and-progression.sql
--
-- Afterwards Hibernate's own update finds everything in place and does nothing.
--
-- The script is idempotent and safe to re-run: every statement is guarded. It
-- runs after 2026-08-course-structure-and-quizzes.sql, which creates the
-- `quizzes`, `quiz_questions` and `quiz_options` tables referenced below.
--
-- Nothing here changes existing data. Progression is derived from these rows
-- plus `completed_lessons`, which is unchanged.
-- =============================================================================


-- --------------------------------------------------------------------------
-- 1. Attempts
-- --------------------------------------------------------------------------
-- score, passing_score and passed are stored rather than recomputed on read:
-- an instructor may edit the quiz or move its pass mark afterwards, and that
-- must not silently rewrite a result the learner has already been given.
--
-- course_id is carried alongside quiz_id on purpose. Quiz ownership is
-- polymorphic, so no join reaches a course from a quiz; storing it is what lets
-- one query load every attempt a learner made inside a course, which is what
-- the progression rules read.
--
-- ON DELETE CASCADE on quiz_id: removing a lesson, module or course removes its
-- quiz, and an attempt at a quiz that no longer exists has nothing left to
-- describe. student_id and course_id deliberately do NOT cascade -- losing a
-- learner's results because a row elsewhere was deleted would be data loss.

CREATE TABLE IF NOT EXISTS quiz_attempts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id         BIGINT       NOT NULL REFERENCES quizzes (id) ON DELETE CASCADE,
    student_id      BIGINT       NOT NULL REFERENCES students (id),
    course_id       BIGINT       NOT NULL REFERENCES courses (id),
    attempt_number  INTEGER      NOT NULL,
    correct_count   INTEGER      NOT NULL,
    total_questions INTEGER      NOT NULL,
    score           INTEGER      NOT NULL,
    passing_score   INTEGER      NOT NULL,
    passed          BOOLEAN      NOT NULL,
    submitted_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_quiz_attempts_student_quiz_number UNIQUE (student_id, quiz_id, attempt_number)
);

-- Progression reads every attempt a student made in one course at once.
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_student_course
    ON quiz_attempts (student_id, course_id);

-- No separate index on (student_id, quiz_id): Postgres backs the unique
-- constraint above with a btree index, and its leading columns are exactly the
-- ones the per-quiz attempt count and pass lookups filter on.


-- --------------------------------------------------------------------------
-- 2. Answers
-- --------------------------------------------------------------------------
-- is_correct is stored, not derived from quiz_options.is_correct on read: the
-- instructor may change which option is right afterwards, and a past attempt
-- must keep saying what it actually said.
--
-- Every foreign key here cascades. An attempt keeps its score and pass state
-- regardless -- those live on quiz_attempts, which only references quizzes --
-- but the per-answer detail of a question or option the instructor has since
-- removed goes with it, which is the only honest thing it can do.

CREATE TABLE IF NOT EXISTS quiz_attempt_answers (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id         BIGINT  NOT NULL REFERENCES quiz_attempts (id) ON DELETE CASCADE,
    question_id        BIGINT  NOT NULL REFERENCES quiz_questions (id) ON DELETE CASCADE,
    selected_option_id BIGINT  NOT NULL REFERENCES quiz_options (id) ON DELETE CASCADE,
    is_correct         BOOLEAN NOT NULL,
    CONSTRAINT uk_quiz_attempt_answers_attempt_question UNIQUE (attempt_id, question_id)
);

CREATE INDEX IF NOT EXISTS idx_quiz_attempt_answers_attempt_id
    ON quiz_attempt_answers (attempt_id);
