-- =============================================================================
-- Course structure (FLAT / MODULES), unified quizzes, access types and plans
-- =============================================================================
--
-- This project has no migration tool: the schema is maintained by Hibernate
-- (`spring.jpa.hibernate.ddl-auto=update`). Hibernate can add tables and columns,
-- but it cannot back-fill existing rows -- and it has no safe way to add a
-- NOT NULL column to a table that already has data. This script does both, and
-- is the authoritative path for the change.
--
-- RUN THIS BEFORE DEPLOYING THE NEW BUILD, against each environment:
--
--     psql "$DATABASE_URL" -f 2026-08-course-structure-and-quizzes.sql
--
-- Afterwards Hibernate's own update finds everything in place and does nothing.
--
-- The script is idempotent and safe to re-run: every statement is guarded, and
-- the back-fills only touch rows that have not been migrated yet. It never drops
-- or rewrites existing course data -- `courses.price` is kept and simply read
-- under its new name.
-- =============================================================================


-- --------------------------------------------------------------------------
-- 1. Course structure, publication state and access type
-- --------------------------------------------------------------------------
-- Defaults are chosen so that rows written before this change describe
-- themselves correctly:
--   * every existing course holds its lessons directly     -> FLAT
--   * every existing course was already live for learners  -> PUBLISHED
-- New courses ignore these defaults; the application always sends a value, and
-- it starts new courses as DRAFT.

ALTER TABLE courses ADD COLUMN IF NOT EXISTS structure   VARCHAR(20) NOT NULL DEFAULT 'FLAT';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS status      VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS access_type VARCHAR(20) NOT NULL DEFAULT 'FREE';

-- Access type used to be implicit in the price. Re-state it explicitly for rows
-- that predate the column. Guarded on the default so a course an instructor has
-- since deliberately made free is never dragged back to PURCHASE: the
-- application clears the price whenever it stores FREE, so a free course cannot
-- match this predicate afterwards.
UPDATE courses
   SET access_type = 'PURCHASE'
 WHERE access_type = 'FREE'
   AND price IS NOT NULL
   AND price > 0;


-- --------------------------------------------------------------------------
-- 2. Modules
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS course_modules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT       NOT NULL REFERENCES courses (id),
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    order_index INTEGER      NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_course_modules_course_id ON course_modules (course_id);


-- --------------------------------------------------------------------------
-- 3. Lessons gain an optional module
-- --------------------------------------------------------------------------
-- Nullable on purpose: a lesson in a FLAT course has no module, and every
-- lesson keeps its course_id either way, which is what leaves all existing
-- course-scoped queries (lesson count, duration, progress) untouched.

ALTER TABLE lessons ADD COLUMN IF NOT EXISTS module_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lessons_module_id') THEN
        ALTER TABLE lessons
            ADD CONSTRAINT fk_lessons_module_id FOREIGN KEY (module_id) REFERENCES course_modules (id);
    END IF;
END
$$;

-- course_id is a foreign key but Postgres does not index those automatically,
-- and every course read filters on it.
CREATE INDEX IF NOT EXISTS idx_lessons_course_id ON lessons (course_id);
CREATE INDEX IF NOT EXISTS idx_lessons_module_id ON lessons (module_id);


-- --------------------------------------------------------------------------
-- 4. Quizzes -- one table for lesson quizzes, module exams and final exams
-- --------------------------------------------------------------------------
-- Ownership is polymorphic, so it cannot carry a foreign key. Two things
-- compensate: the unique constraint below enforces "at most one quiz per
-- owner" in the database, and the application deletes an owner's quiz in the
-- same transaction that deletes the owner.

CREATE TABLE IF NOT EXISTS quizzes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type    VARCHAR(20)  NOT NULL,
    owner_id      BIGINT       NOT NULL,
    title         VARCHAR(255) NOT NULL,
    instructions  TEXT,
    passing_score INTEGER      NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6),
    CONSTRAINT uk_quizzes_owner UNIQUE (owner_type, owner_id)
);

-- No separate index on (owner_type, owner_id): Postgres backs the unique
-- constraint above with a btree index, which every owner lookup already uses.

CREATE TABLE IF NOT EXISTS quiz_questions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id             BIGINT  NOT NULL REFERENCES quizzes (id) ON DELETE CASCADE,
    text                TEXT    NOT NULL,
    explanation         TEXT,
    hint_by_ai_enabled  BOOLEAN NOT NULL DEFAULT FALSE,
    order_index         INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_quiz_questions_quiz_id ON quiz_questions (quiz_id);

-- The answer key is a flag on the option rather than a correct_option_id on the
-- question: that keeps the two tables free of a reference cycle, so a brand-new
-- quiz can be written in a single pass.
CREATE TABLE IF NOT EXISTS quiz_options (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT  NOT NULL REFERENCES quiz_questions (id) ON DELETE CASCADE,
    text        TEXT    NOT NULL,
    is_correct  BOOLEAN NOT NULL DEFAULT FALSE,
    order_index INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_quiz_options_question_id ON quiz_options (question_id);

-- At most one correct option per question. A partial unique index expresses this
-- exactly; the application validates it too, so the two agree.
CREATE UNIQUE INDEX IF NOT EXISTS uk_quiz_options_single_correct
    ON quiz_options (question_id) WHERE is_correct;


-- --------------------------------------------------------------------------
-- 5. Subscription plans
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS subscription_plans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT        NOT NULL REFERENCES courses (id),
    name        VARCHAR(255)  NOT NULL,
    duration    INTEGER       NOT NULL,
    unit        VARCHAR(20)   NOT NULL,
    price       NUMERIC(38, 2) NOT NULL,
    order_index INTEGER       NOT NULL,
    created_at  TIMESTAMP(6)  NOT NULL,
    updated_at  TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_subscription_plans_course_id ON subscription_plans (course_id);
