-- =============================================================================
-- V18 — email_change_requests: a signed-in account asking to move to a new address
-- =============================================================================
--
-- One row per request. The code sent to the new address is never stored: only an
-- HMAC of it, keyed by a server secret and bound to the request id and the resend
-- generation, so a copy of this table does not yield a usable code.
--
-- status
--   PENDING     waiting for the code; at most one per account (partial index below)
--   CONSUMED    the code was accepted once; the account's address changed
--   SUPERSEDED  replaced by a newer request from the same account
--   LOCKED      too many wrong codes; a new request is needed
--
-- target_unavailable is true when the address already belonged to another account
-- at request time. Such a request is answered exactly like any other, but no code
-- is ever sent, so it can never complete. It exists so the response cannot tell the
-- caller whether the address is registered.
--
-- DEPLOYMENT COMPATIBILITY: a new table only. The previous build never reads it.
-- =============================================================================

CREATE TABLE public.email_change_requests (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id           uuid                           NOT NULL,
    user_id              bigint                         NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    new_email            varchar(255)                   NOT NULL,
    code_hash            varchar(64)                    NOT NULL,
    status               varchar(20)                    NOT NULL,
    target_unavailable   boolean                        NOT NULL DEFAULT false,
    attempts             integer                        NOT NULL DEFAULT 0,
    resend_count         integer                        NOT NULL DEFAULT 0,
    expires_at           timestamp(6) without time zone NOT NULL,
    resend_available_at  timestamp(6) without time zone NOT NULL,
    created_at           timestamp(6) without time zone NOT NULL,
    consumed_at          timestamp(6) without time zone,
    CONSTRAINT uk_email_change_requests_request_id UNIQUE (request_id),
    CONSTRAINT ck_email_change_requests_status
        CHECK (status IN ('PENDING', 'CONSUMED', 'SUPERSEDED', 'LOCKED')),
    CONSTRAINT ck_email_change_requests_email_canonical CHECK (new_email = lower(btrim(new_email)))
);

CREATE UNIQUE INDEX uk_email_change_requests_one_pending
    ON public.email_change_requests (user_id)
    WHERE status = 'PENDING';

CREATE INDEX idx_email_change_requests_user_created
    ON public.email_change_requests (user_id, created_at DESC);
