-- =============================================================================
-- V19 — course categories, and the instructor's public headline
-- =============================================================================
--
-- course_categories
--   The catalogue's category lookup: a stable id, an Arabic display name, and a
--   colour taken from a fixed allow-list of design tokens (never a free colour).
--   Deliberately NOT seeded: no approved taxonomy exists yet, and inventing one
--   would put categories on public pages nobody chose. Until rows are added,
--   every course's category is NULL and the public pages show no chip.
--
-- courses.category_id
--   Nullable. NULL means "uncategorised", which is also what every existing
--   course is after this migration. ON DELETE SET NULL: removing a category
--   uncategorises its courses rather than failing or deleting them.
--
-- instructors.headline
--   A short public line under the instructor's name on course pages (≤ 120
--   characters, plain text). NULL for everyone until an instructor writes one.
--
-- DEPLOYMENT COMPATIBILITY: additive only. The previous build never reads these
-- columns, and its inserts leave them NULL.
-- =============================================================================

CREATE TABLE public.course_categories (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         varchar(60)                    NOT NULL,
    name_ar      varchar(60)                    NOT NULL,
    color_token  varchar(20)                    NOT NULL,
    sort_order   integer                        NOT NULL DEFAULT 0,
    active       boolean                        NOT NULL DEFAULT true,
    created_at   timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uk_course_categories_slug UNIQUE (slug),
    CONSTRAINT ck_course_categories_color_token
        CHECK (color_token IN ('indigo', 'teal', 'amber', 'rose', 'violet', 'emerald', 'sky', 'slate'))
);

ALTER TABLE public.courses
    ADD COLUMN IF NOT EXISTS category_id bigint
        REFERENCES public.course_categories (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_courses_category_id ON public.courses (category_id);

ALTER TABLE public.instructors
    ADD COLUMN IF NOT EXISTS headline varchar(120);
