-- =============================================================================
-- V1 — Baseline schema
-- =============================================================================
--
-- This is the schema as it stood the moment Flyway took ownership of it, and it
-- is the point every future migration builds on. Do not edit this file: Flyway
-- records a checksum of it, and changing it after it has been applied anywhere
-- makes that database fail to start.
--
-- How it was produced, so the provenance is auditable:
--
--   1. An empty PostgreSQL 17.5 database was created.
--   2. The application was started with spring.jpa.hibernate.ddl-auto=update, so
--      Hibernate created every table and column from the JPA entity model. That
--      is exactly what produced the schema running today.
--   3. The six hand-written scripts in src/main/resources/db/ were applied in the
--      order they were committed. They are not redundant: `ddl-auto=update` never
--      adds a constraint or index to a table that already exists, so the unique
--      constraints, partial indexes and foreign keys they declare exist ONLY
--      because someone ran those scripts by hand. Folding them in here is what
--      stops that from ever being forgotten again.
--   4. `pg_dump --schema-only --no-owner --no-privileges` captured the result.
--
-- pg_dump's session-configuration preamble was removed. Those SET statements
-- configure the dumping session, and its `search_path = ''` in particular would
-- change how Flyway's own session resolves unqualified names. Every object below
-- is schema-qualified, so nothing depends on them.
--
-- Existing databases are NOT re-created by this file. spring.flyway.baseline-on-
-- migrate=true means a database that already has this schema is simply recorded
-- at version 1 and left untouched; only a genuinely empty database runs it.
-- =============================================================================

--
--

--
-- Name: banner_dismissals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.banner_dismissals (
    id bigint NOT NULL,
    dismissed_at timestamp(6) without time zone NOT NULL,
    banner_id bigint NOT NULL,
    student_id bigint NOT NULL
);

--
-- Name: banner_dismissals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.banner_dismissals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banner_dismissals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: banners; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.banners (
    id bigint NOT NULL,
    cta_label character varying(255),
    cta_url character varying(1024),
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    dismissible boolean NOT NULL,
    display_frequency character varying(32) NOT NULL,
    draft boolean NOT NULL,
    enabled boolean NOT NULL,
    end_at timestamp(6) without time zone,
    image_url character varying(1024),
    internal_name character varying(255) NOT NULL,
    priority integer NOT NULL,
    start_at timestamp(6) without time zone,
    timezone character varying(64) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    instructor_id bigint NOT NULL,
    CONSTRAINT banners_display_frequency_check CHECK (((display_frequency)::text = ANY ((ARRAY['EVERY_VISIT'::character varying, 'ONCE_PER_SESSION'::character varying, 'ONCE_PER_STUDENT'::character varying])::text[])))
);

--
-- Name: banners_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.banners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: completed_lessons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.completed_lessons (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone NOT NULL,
    lesson_id bigint NOT NULL,
    student_id bigint NOT NULL
);

--
-- Name: completed_lessons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.completed_lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.completed_lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: course_entitlements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_entitlements (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone,
    source character varying(20) NOT NULL,
    starts_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    subscription_plan_id bigint,
    CONSTRAINT course_entitlements_source_check CHECK (((source)::text = ANY ((ARRAY['FREE'::character varying, 'PURCHASE'::character varying, 'SUBSCRIPTION'::character varying])::text[])))
);

--
-- Name: course_entitlements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_entitlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_entitlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: course_modules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_modules (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    order_index integer NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    course_id bigint NOT NULL
);

--
-- Name: course_modules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_modules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_modules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: course_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_subscriptions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    payment_reference character varying(100),
    price_paid numeric(38,2) NOT NULL,
    starts_at timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    course_id bigint NOT NULL,
    subscription_plan_id bigint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT course_subscriptions_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying])::text[])))
);

--
-- Name: course_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id bigint NOT NULL,
    access_type character varying(20) DEFAULT 'FREE'::character varying NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    duration integer,
    image character varying(255),
    price numeric(38,2),
    status character varying(20) DEFAULT 'PUBLISHED'::character varying NOT NULL,
    structure character varying(20) DEFAULT 'FLAT'::character varying NOT NULL,
    students_count integer NOT NULL,
    subtitle character varying(255),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    instructor_id bigint NOT NULL,
    CONSTRAINT courses_access_type_check CHECK (((access_type)::text = ANY ((ARRAY['FREE'::character varying, 'PURCHASE'::character varying, 'SUBSCRIPTION'::character varying])::text[]))),
    CONSTRAINT courses_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[]))),
    CONSTRAINT courses_structure_check CHECK (((structure)::text = ANY ((ARRAY['FLAT'::character varying, 'MODULES'::character varying])::text[])))
);

--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: enrollments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enrollments (
    id bigint NOT NULL,
    enrolled boolean NOT NULL,
    enrolled_at timestamp(6) without time zone NOT NULL,
    progress integer NOT NULL,
    course_id bigint NOT NULL,
    student_id bigint NOT NULL
);

--
-- Name: enrollments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enrollments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: instructors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instructors (
    id bigint NOT NULL,
    bio text,
    specialization character varying(255),
    user_id bigint NOT NULL
);

--
-- Name: instructors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instructors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instructors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: lessons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lessons (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    duration integer,
    order_index integer NOT NULL,
    summary text,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    external_video_id character varying(128),
    video_provider character varying(32),
    video_thumbnail_url text,
    video_url text NOT NULL,
    course_id bigint NOT NULL,
    module_id bigint,
    CONSTRAINT lessons_video_provider_check CHECK (((video_provider)::text = ANY ((ARRAY['YOUTUBE'::character varying, 'VIMEO'::character varying])::text[])))
);

--
-- Name: lessons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: otps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otps (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT otps_type_check CHECK (((type)::text = ANY ((ARRAY['EMAIL_VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying])::text[])))
);

--
-- Name: otps_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.otps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: quiz_attempt_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_attempt_answers (
    id bigint NOT NULL,
    is_correct boolean NOT NULL,
    attempt_id bigint NOT NULL,
    question_id bigint NOT NULL,
    selected_option_id bigint NOT NULL
);

--
-- Name: quiz_attempt_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_attempt_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_attempt_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: quiz_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_attempts (
    id bigint NOT NULL,
    attempt_number integer NOT NULL,
    correct_count integer NOT NULL,
    passed boolean NOT NULL,
    passing_score integer NOT NULL,
    score integer NOT NULL,
    submitted_at timestamp(6) without time zone NOT NULL,
    total_questions integer NOT NULL,
    course_id bigint NOT NULL,
    quiz_id bigint NOT NULL,
    student_id bigint NOT NULL
);

--
-- Name: quiz_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: quiz_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_options (
    id bigint NOT NULL,
    is_correct boolean DEFAULT false NOT NULL,
    order_index integer NOT NULL,
    text text NOT NULL,
    question_id bigint NOT NULL
);

--
-- Name: quiz_options_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: quiz_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_questions (
    id bigint NOT NULL,
    explanation text,
    hint_by_ai_enabled boolean DEFAULT false NOT NULL,
    order_index integer NOT NULL,
    text text NOT NULL,
    quiz_id bigint NOT NULL
);

--
-- Name: quiz_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: quizzes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quizzes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    instructions text,
    owner_id bigint NOT NULL,
    owner_type character varying(20) NOT NULL,
    passing_score integer NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT quizzes_owner_type_check CHECK (((owner_type)::text = ANY ((ARRAY['COURSE'::character varying, 'MODULE'::character varying, 'LESSON'::character varying])::text[])))
);

--
-- Name: quizzes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quizzes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quizzes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: subscription_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscription_plans (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    duration integer NOT NULL,
    name character varying(255) NOT NULL,
    order_index integer NOT NULL,
    price numeric(38,2) NOT NULL,
    unit character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    course_id bigint NOT NULL,
    CONSTRAINT subscription_plans_unit_check CHECK (((unit)::text = ANY ((ARRAY['DAY'::character varying, 'WEEK'::character varying, 'MONTH'::character varying])::text[])))
);

--
-- Name: subscription_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscription_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    email_verified boolean NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    requires_password_reset boolean NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'INSTRUCTOR'::character varying, 'ADMIN'::character varying])::text[])))
);

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: banner_dismissals banner_dismissals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banner_dismissals
    ADD CONSTRAINT banner_dismissals_pkey PRIMARY KEY (id);

--
-- Name: banners banners_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banners
    ADD CONSTRAINT banners_pkey PRIMARY KEY (id);

--
-- Name: completed_lessons completed_lessons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.completed_lessons
    ADD CONSTRAINT completed_lessons_pkey PRIMARY KEY (id);

--
-- Name: course_entitlements course_entitlements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_entitlements
    ADD CONSTRAINT course_entitlements_pkey PRIMARY KEY (id);

--
-- Name: course_modules course_modules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_modules
    ADD CONSTRAINT course_modules_pkey PRIMARY KEY (id);

--
-- Name: course_subscriptions course_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_subscriptions
    ADD CONSTRAINT course_subscriptions_pkey PRIMARY KEY (id);

--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);

--
-- Name: enrollments enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT enrollments_pkey PRIMARY KEY (id);

--
-- Name: instructors instructors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructors
    ADD CONSTRAINT instructors_pkey PRIMARY KEY (id);

--
-- Name: lessons lessons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);

--
-- Name: otps otps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otps
    ADD CONSTRAINT otps_pkey PRIMARY KEY (id);

--
-- Name: quiz_attempt_answers quiz_attempt_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempt_answers
    ADD CONSTRAINT quiz_attempt_answers_pkey PRIMARY KEY (id);

--
-- Name: quiz_attempts quiz_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempts
    ADD CONSTRAINT quiz_attempts_pkey PRIMARY KEY (id);

--
-- Name: quiz_options quiz_options_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_options
    ADD CONSTRAINT quiz_options_pkey PRIMARY KEY (id);

--
-- Name: quiz_questions quiz_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT quiz_questions_pkey PRIMARY KEY (id);

--
-- Name: quizzes quizzes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT quizzes_pkey PRIMARY KEY (id);

--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);

--
-- Name: subscription_plans subscription_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription_plans
    ADD CONSTRAINT subscription_plans_pkey PRIMARY KEY (id);

--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

--
-- Name: instructors uk9bnko4773vvkd5f2pdbxvsly3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructors
    ADD CONSTRAINT uk9bnko4773vvkd5f2pdbxvsly3 UNIQUE (user_id);

--
-- Name: banner_dismissals uk_banner_dismissals_banner_student; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banner_dismissals
    ADD CONSTRAINT uk_banner_dismissals_banner_student UNIQUE (banner_id, student_id);

--
-- Name: course_entitlements uk_course_entitlements_course_student; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_entitlements
    ADD CONSTRAINT uk_course_entitlements_course_student UNIQUE (course_id, student_id);

--
-- Name: enrollments uk_enrollments_course_student; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT uk_enrollments_course_student UNIQUE (course_id, student_id);

--
-- Name: quiz_attempt_answers uk_quiz_attempt_answers_attempt_question; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempt_answers
    ADD CONSTRAINT uk_quiz_attempt_answers_attempt_question UNIQUE (attempt_id, question_id);

--
-- Name: quiz_attempts uk_quiz_attempts_student_quiz_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempts
    ADD CONSTRAINT uk_quiz_attempts_student_quiz_number UNIQUE (student_id, quiz_id, attempt_number);

--
-- Name: quizzes uk_quizzes_owner; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT uk_quizzes_owner UNIQUE (owner_type, owner_id);

--
-- Name: students ukg4fwvutq09fjdlb4bb0byp7t; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT ukg4fwvutq09fjdlb4bb0byp7t UNIQUE (user_id);

--
-- Name: completed_lessons ukg5ym59e43wnkg0t14fej8bp0d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.completed_lessons
    ADD CONSTRAINT ukg5ym59e43wnkg0t14fej8bp0d UNIQUE (student_id, lesson_id);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: idx_banner_dismissals_student_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_banner_dismissals_student_id ON public.banner_dismissals USING btree (student_id);

--
-- Name: idx_banners_instructor_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_banners_instructor_id ON public.banners USING btree (instructor_id);

--
-- Name: idx_banners_priority; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_banners_priority ON public.banners USING btree (priority);

--
-- Name: idx_course_modules_course_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_modules_course_id ON public.course_modules USING btree (course_id);

--
-- Name: idx_course_subscriptions_course_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_subscriptions_course_id ON public.course_subscriptions USING btree (course_id);

--
-- Name: idx_course_subscriptions_student_course; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_subscriptions_student_course ON public.course_subscriptions USING btree (student_id, course_id);

--
-- Name: idx_lessons_course_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lessons_course_id ON public.lessons USING btree (course_id);

--
-- Name: idx_lessons_module_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lessons_module_id ON public.lessons USING btree (module_id);

--
-- Name: idx_lessons_video_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lessons_video_provider ON public.lessons USING btree (video_provider);

--
-- Name: idx_quiz_attempt_answers_attempt_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_quiz_attempt_answers_attempt_id ON public.quiz_attempt_answers USING btree (attempt_id);

--
-- Name: idx_quiz_attempts_student_course; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_quiz_attempts_student_course ON public.quiz_attempts USING btree (student_id, course_id);

--
-- Name: idx_quiz_options_question_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_quiz_options_question_id ON public.quiz_options USING btree (question_id);

--
-- Name: idx_quiz_questions_quiz_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_quiz_questions_quiz_id ON public.quiz_questions USING btree (quiz_id);

--
-- Name: idx_subscription_plans_course_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subscription_plans_course_id ON public.subscription_plans USING btree (course_id);

--
-- Name: uk_quiz_options_single_correct; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_quiz_options_single_correct ON public.quiz_options USING btree (question_id) WHERE is_correct;

--
-- Name: lessons fk17ucc7gjfjddsyi0gvstkqeat; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk17ucc7gjfjddsyi0gvstkqeat FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: courses fk1kswo6qqebbdy2kq0kx6udof7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk1kswo6qqebbdy2kq0kx6udof7 FOREIGN KEY (instructor_id) REFERENCES public.instructors(id);

--
-- Name: quiz_attempt_answers fk54g2hjt484k0nnvfx9kj1j8qe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempt_answers
    ADD CONSTRAINT fk54g2hjt484k0nnvfx9kj1j8qe FOREIGN KEY (selected_option_id) REFERENCES public.quiz_options(id) ON DELETE CASCADE;

--
-- Name: quiz_attempt_answers fk59s9075rs7i5520p8awj6ri1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempt_answers
    ADD CONSTRAINT fk59s9075rs7i5520p8awj6ri1 FOREIGN KEY (question_id) REFERENCES public.quiz_questions(id) ON DELETE CASCADE;

--
-- Name: course_entitlements fk5c7lf48nkhww121rd3m2jhlov; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_entitlements
    ADD CONSTRAINT fk5c7lf48nkhww121rd3m2jhlov FOREIGN KEY (subscription_plan_id) REFERENCES public.subscription_plans(id);

--
-- Name: quiz_attempts fk8fu3xdfv85qh8v2xgbyi0iahu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempts
    ADD CONSTRAINT fk8fu3xdfv85qh8v2xgbyi0iahu FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: enrollments fk8kf1u1857xgo56xbfmnif2c51; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fk8kf1u1857xgo56xbfmnif2c51 FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: banner_dismissals fk8ycftg98yux4hnfv7ynfb4r93; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banner_dismissals
    ADD CONSTRAINT fk8ycftg98yux4hnfv7ynfb4r93 FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: banner_dismissals fk9cfovh64hx9fauc2p3nahw63k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banner_dismissals
    ADD CONSTRAINT fk9cfovh64hx9fauc2p3nahw63k FOREIGN KEY (banner_id) REFERENCES public.banners(id);

--
-- Name: lessons fk_lessons_module_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk_lessons_module_id FOREIGN KEY (module_id) REFERENCES public.course_modules(id);

--
-- Name: subscription_plans fkackrm10n6td800fdubo3aorjd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription_plans
    ADD CONSTRAINT fkackrm10n6td800fdubo3aorjd FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: quiz_questions fkanfmgf6ksbdnv7ojb0pfve54q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT fkanfmgf6ksbdnv7ojb0pfve54q FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id);

--
-- Name: course_subscriptions fkbhdhvvhtkw78gtc3gqxssq24e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_subscriptions
    ADD CONSTRAINT fkbhdhvvhtkw78gtc3gqxssq24e FOREIGN KEY (subscription_plan_id) REFERENCES public.subscription_plans(id);

--
-- Name: course_entitlements fkcyxg3l5remoo3n7kf0ld5irrn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_entitlements
    ADD CONSTRAINT fkcyxg3l5remoo3n7kf0ld5irrn FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: instructors fkds2m3jgxj98sd5mr1qw23ecjp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructors
    ADD CONSTRAINT fkds2m3jgxj98sd5mr1qw23ecjp FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: students fkdt1cjx5ve5bdabmuuf3ibrwaq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkdt1cjx5ve5bdabmuuf3ibrwaq FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: quiz_attempts fkfwipvfipnnwsoacoyv5k7fbxc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempts
    ADD CONSTRAINT fkfwipvfipnnwsoacoyv5k7fbxc FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id) ON DELETE CASCADE;

--
-- Name: completed_lessons fkgc9n06ular8rdmjfb5sreyplx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.completed_lessons
    ADD CONSTRAINT fkgc9n06ular8rdmjfb5sreyplx FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: quiz_attempts fkgewyjbecvscpilqy5wf54jwd1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempts
    ADD CONSTRAINT fkgewyjbecvscpilqy5wf54jwd1 FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: quiz_options fkhkuvmd7qk1lmtq3hy9htpinkr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_options
    ADD CONSTRAINT fkhkuvmd7qk1lmtq3hy9htpinkr FOREIGN KEY (question_id) REFERENCES public.quiz_questions(id);

--
-- Name: enrollments fkho8mcicp4196ebpltdn9wl6co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fkho8mcicp4196ebpltdn9wl6co FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: banners fkn83speo8539ox3ytgg87wr4qp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banners
    ADD CONSTRAINT fkn83speo8539ox3ytgg87wr4qp FOREIGN KEY (instructor_id) REFERENCES public.instructors(id);

--
-- Name: lessons fkqfp7ioroqawsicj32pxfnggm8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fkqfp7ioroqawsicj32pxfnggm8 FOREIGN KEY (module_id) REFERENCES public.course_modules(id);

--
-- Name: course_entitlements fkql1y37o33kuxj6w0puupsreyt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_entitlements
    ADD CONSTRAINT fkql1y37o33kuxj6w0puupsreyt FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: quiz_attempt_answers fkqo1br76p5c2piffjoaiqm5yuu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempt_answers
    ADD CONSTRAINT fkqo1br76p5c2piffjoaiqm5yuu FOREIGN KEY (attempt_id) REFERENCES public.quiz_attempts(id) ON DELETE CASCADE;

--
-- Name: completed_lessons fkr4x93qop2q19mtydl4yc40h36; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.completed_lessons
    ADD CONSTRAINT fkr4x93qop2q19mtydl4yc40h36 FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);

--
-- Name: course_subscriptions fkrecjhc1j4qnr48moy75c2cqje; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_subscriptions
    ADD CONSTRAINT fkrecjhc1j4qnr48moy75c2cqje FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: course_subscriptions fkrow0qblafb4waeut288mf7rpa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_subscriptions
    ADD CONSTRAINT fkrow0qblafb4waeut288mf7rpa FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: otps fkseso6nlp9f5fbuilrngn3pbyi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otps
    ADD CONSTRAINT fkseso6nlp9f5fbuilrngn3pbyi FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: course_modules fktn63pa8l33002k4xuwkcuefll; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_modules
    ADD CONSTRAINT fktn63pa8l33002k4xuwkcuefll FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
--
