-- =============================================================================
-- V20 — payment_transactions and payment_receipts
-- =============================================================================
--
-- payment_transactions
--   One row per charge the platform took for a course: what it was for, what
--   was recorded as charged, its status, and — the column everything reported
--   to a learner depends on — its PROVENANCE:
--
--     LIVE       charged by a real payment provider (none is integrated yet)
--     SIMULATED  charged by the simulator: no money moved
--     LEGACY     predates this table; the amount is what the purchase or
--                subscription row recorded, but nothing more is known
--
--   Only LIVE rows ever count towards a "total paid" figure.
--
-- payment_receipts
--   An immutable snapshot issued for a PAID transaction the application
--   recorded itself: customer, line, amount and currency as they were at the
--   time. Numbers come from a sequence, so they are unique but may have gaps;
--   they are not a legal invoice series. Simulated receipts are numbered DEMO-.
--
-- BACKFILL (below)
--   Existing course_purchases and course_subscriptions become LEGACY or
--   SIMULATED transactions, using only what those rows recorded: the amount,
--   the gateway reference (a `sim_` reference is the simulator's), and the
--   time. Nothing is inferred from today's prices, and no receipt is created
--   for them — a receipt that was never issued is not invented now. Each row
--   carries a source_key (purchase:<id> / subscription:<id>), and a row that
--   already has a transaction — backfilled, or recorded by checkout — is
--   skipped, so running the INSERTs again at any later time adds nothing.
--
--   Currency: course_purchases records it. course_subscriptions does not;
--   every charge path has only ever charged EGP (CheckoutProcessor.CURRENCY),
--   and those rows are recorded as EGP on that basis.
--
-- DEPLOYMENT COMPATIBILITY: new tables and a sequence only; existing tables are
-- read, not altered. The previous build never touches them.
-- =============================================================================

CREATE TABLE public.payment_transactions (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference             uuid                           NOT NULL,
    student_id            bigint                         NOT NULL REFERENCES public.students (id),
    course_id             bigint                         NOT NULL REFERENCES public.courses (id),
    purpose               varchar(20)                    NOT NULL,
    purchase_id           bigint                                  REFERENCES public.course_purchases (id),
    subscription_id       bigint                                  REFERENCES public.course_subscriptions (id),
    subscription_plan_id  bigint                                  REFERENCES public.subscription_plans (id),
    line_description      varchar(255)                   NOT NULL,
    amount                numeric(12, 2),
    currency              varchar(3),
    status                varchar(30)                    NOT NULL,
    provenance            varchar(20)                    NOT NULL,
    gateway_reference     varchar(100),
    refunded_amount       numeric(12, 2)                 NOT NULL DEFAULT 0,
    created_at            timestamp(6) without time zone NOT NULL,
    paid_at               timestamp(6) without time zone,
    source_key            varchar(80)                    NOT NULL,
    CONSTRAINT uk_payment_transactions_reference UNIQUE (reference),
    CONSTRAINT uk_payment_transactions_source_key UNIQUE (source_key),
    CONSTRAINT uk_payment_transactions_purchase UNIQUE (purchase_id),
    CONSTRAINT uk_payment_transactions_subscription UNIQUE (subscription_id),
    CONSTRAINT ck_payment_transactions_purpose CHECK (purpose IN ('PURCHASE', 'SUBSCRIPTION')),
    CONSTRAINT ck_payment_transactions_status CHECK (status IN
        ('AWAITING_PAYMENT', 'PROCESSING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED')),
    CONSTRAINT ck_payment_transactions_provenance CHECK (provenance IN ('LIVE', 'SIMULATED', 'LEGACY')),
    CONSTRAINT ck_payment_transactions_amount CHECK (amount IS NULL OR amount >= 0),
    CONSTRAINT ck_payment_transactions_link CHECK (
        (purpose = 'PURCHASE' AND subscription_id IS NULL)
        OR (purpose = 'SUBSCRIPTION' AND purchase_id IS NULL))
);

CREATE INDEX idx_payment_transactions_student_created
    ON public.payment_transactions (student_id, created_at DESC, id DESC);

CREATE SEQUENCE public.payment_receipt_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE public.payment_receipts (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number             varchar(40)                    NOT NULL,
    transaction_id     bigint                         NOT NULL REFERENCES public.payment_transactions (id),
    issued_at          timestamp(6) without time zone NOT NULL,
    simulated          boolean                        NOT NULL,
    customer_name      varchar(255)                   NOT NULL,
    customer_email     varchar(255)                   NOT NULL,
    line_description   varchar(255)                   NOT NULL,
    amount             numeric(12, 2)                 NOT NULL,
    currency           varchar(3)                     NOT NULL,
    gateway_reference  varchar(100),
    CONSTRAINT uk_payment_receipts_number UNIQUE (number),
    CONSTRAINT uk_payment_receipts_transaction UNIQUE (transaction_id)
);

-- Backfill: purchases ---------------------------------------------------------

INSERT INTO public.payment_transactions
    (reference, student_id, course_id, purpose, purchase_id, line_description, amount, currency,
     status, provenance, gateway_reference, created_at, paid_at, source_key)
SELECT gen_random_uuid(), p.student_id, p.course_id, 'PURCHASE', p.id,
       left(c.title, 255), p.amount_paid, p.currency, 'PAID',
       CASE WHEN p.payment_reference LIKE 'sim\_%' THEN 'SIMULATED' ELSE 'LEGACY' END,
       p.payment_reference, p.purchased_at, p.purchased_at, 'purchase:' || p.id
FROM public.course_purchases p
JOIN public.courses c ON c.id = p.course_id
WHERE NOT EXISTS (SELECT 1 FROM public.payment_transactions t WHERE t.purchase_id = p.id)
ON CONFLICT (source_key) DO NOTHING;

-- Backfill: subscriptions -----------------------------------------------------

INSERT INTO public.payment_transactions
    (reference, student_id, course_id, purpose, subscription_id, subscription_plan_id, line_description,
     amount, currency, status, provenance, gateway_reference, created_at, paid_at, source_key)
SELECT gen_random_uuid(), s.student_id, s.course_id, 'SUBSCRIPTION', s.id, s.subscription_plan_id,
       left(c.title || ' - ' || pl.name, 255), s.price_paid, 'EGP', 'PAID',
       CASE WHEN s.payment_reference LIKE 'sim\_%' THEN 'SIMULATED' ELSE 'LEGACY' END,
       s.payment_reference, s.created_at, s.created_at, 'subscription:' || s.id
FROM public.course_subscriptions s
JOIN public.courses c ON c.id = s.course_id
JOIN public.subscription_plans pl ON pl.id = s.subscription_plan_id
WHERE NOT EXISTS (SELECT 1 FROM public.payment_transactions t WHERE t.subscription_id = s.id)
ON CONFLICT (source_key) DO NOTHING;
