-- =============================================================================
-- V21 — refund_requests
-- =============================================================================
--
-- A student's request to be refunded for one transaction, and the review
-- decision on it. This is the REQUEST, kept apart from the transaction's
-- payment state and from any provider refund operation: submitting, approving
-- or rejecting a request changes neither the transaction, its paid total, nor
-- course access. Money is returned only by a provider refund, which a later
-- change records against the transaction when one is integrated.
--
-- The amount is the server's: what remains refundable on the transaction when
-- the request was made. The student never supplies it. A reason is optional:
-- the published Terms (1.0, section 6) grant the refund without one.
--
-- At most one request per transaction is open (SUBMITTED or APPROVED); a
-- rejected request does not prevent a later one. The partial unique index is
-- what holds that under concurrent submissions.
--
-- Accepting requests is off unless app.refund-requests.enabled is set, because
-- no reviewer surface exists yet; see docs/api/STUDENT_BILLING_API.md.
--
-- DEPLOYMENT COMPATIBILITY: a new table only. The previous build never reads it.
-- =============================================================================

CREATE TABLE public.refund_requests (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference       uuid                           NOT NULL,
    transaction_id  bigint                         NOT NULL REFERENCES public.payment_transactions (id),
    student_id      bigint                         NOT NULL REFERENCES public.students (id),
    reason          varchar(30),
    note            varchar(1000),
    amount          numeric(12, 2)                 NOT NULL,
    currency        varchar(3)                     NOT NULL,
    status          varchar(20)                    NOT NULL,
    created_at      timestamp(6) without time zone NOT NULL,
    decided_at      timestamp(6) without time zone,
    decision_note   varchar(1000),
    CONSTRAINT uk_refund_requests_reference UNIQUE (reference),
    CONSTRAINT ck_refund_requests_reason CHECK (reason IS NULL OR reason IN
        ('ACCESS_PROBLEM', 'NOT_AS_DESCRIBED', 'DUPLICATE_CHARGE', 'CHANGED_MIND', 'OTHER')),
    CONSTRAINT ck_refund_requests_status CHECK (status IN ('SUBMITTED', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_refund_requests_amount CHECK (amount > 0),
    CONSTRAINT ck_refund_requests_decision CHECK ((status = 'SUBMITTED') = (decided_at IS NULL))
);

CREATE UNIQUE INDEX uk_refund_requests_one_open_per_transaction
    ON public.refund_requests (transaction_id)
    WHERE status IN ('SUBMITTED', 'APPROVED');

CREATE INDEX idx_refund_requests_transaction_created
    ON public.refund_requests (transaction_id, created_at DESC, id DESC);
